/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Guestbook service. Represents a row in the &quot;guest_books2&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.services.model.impl.GuestbookModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.services.model.impl.GuestbookImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Guestbook
 * @generated
 */
@ProviderType
public interface GuestbookModel extends BaseModel<Guestbook> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a guestbook model instance should use the {@link Guestbook} interface instead.
	 */

	/**
	 * Returns the primary key of this guestbook.
	 *
	 * @return the primary key of this guestbook
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this guestbook.
	 *
	 * @param primaryKey the primary key of this guestbook
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the my ID of this guestbook.
	 *
	 * @return the my ID of this guestbook
	 */
	public long getMyId();

	/**
	 * Sets the my ID of this guestbook.
	 *
	 * @param myId the my ID of this guestbook
	 */
	public void setMyId(long myId);

	/**
	 * Returns the name of this guestbook.
	 *
	 * @return the name of this guestbook
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this guestbook.
	 *
	 * @param name the name of this guestbook
	 */
	public void setName(String name);

	/**
	 * Returns the my date of this guestbook.
	 *
	 * @return the my date of this guestbook
	 */
	@AutoEscape
	public String getMyDate();

	/**
	 * Sets the my date of this guestbook.
	 *
	 * @param myDate the my date of this guestbook
	 */
	public void setMyDate(String myDate);

	/**
	 * Returns the message of this guestbook.
	 *
	 * @return the message of this guestbook
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this guestbook.
	 *
	 * @param message the message of this guestbook
	 */
	public void setMessage(String message);

	/**
	 * Returns the created ID of this guestbook.
	 *
	 * @return the created ID of this guestbook
	 */
	public long getCreatedId();

	/**
	 * Sets the created ID of this guestbook.
	 *
	 * @param createdId the created ID of this guestbook
	 */
	public void setCreatedId(long createdId);

	/**
	 * Returns the image url of this guestbook.
	 *
	 * @return the image url of this guestbook
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this guestbook.
	 *
	 * @param imageUrl the image url of this guestbook
	 */
	public void setImageUrl(String imageUrl);

}